import express from 'express';
import session from 'express-session';
import multer from 'multer';
import path from 'node:path';
import fs from 'node:fs';
import crypto from 'node:crypto';
import db,{getRecruitments,getRecruitment,createRecruitment,createApplication,hasRecentApplication,getApplications,getApplicationsForUser,updateApplication,getSetting,setSetting,stats,audit,getAuditLogs,createTicket,getTickets,getTicketsForUser,setTicketStatus,setRecruitmentStatus} from './db.js';
import {publishFromDashboard,notifyWebsiteApplication,notifyWebsiteApplicationStatus,notifyWebsiteTicket} from './bot.js';

const app=express();
const uploadDir=path.resolve('data/uploads');
fs.mkdirSync(uploadDir,{recursive:true});
const upload=multer({
 storage:multer.diskStorage({destination:uploadDir,filename:(req,file,cb)=>cb(null,`${Date.now()}-${crypto.randomUUID()}${path.extname(file.originalname).toLowerCase()}`)}),
 limits:{fileSize:8*1024*1024},
 fileFilter:(req,file,cb)=>cb(null,/^(image\/(png|jpe?g|webp|gif)|application\/pdf)$/.test(file.mimetype))
});
app.use(express.json({limit:'1mb'}));
app.use(express.urlencoded({extended:true}));
app.use(express.static('public'));
app.use('/uploads',express.static(uploadDir));
app.use(session({secret:process.env.SESSION_SECRET||'dev-secret',resave:false,saveUninitialized:false,cookie:{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:7*86400000}}));

const clean=(v,max)=>String(v??'').trim().slice(0,max);
const publicGuildId=()=>process.env.DEFAULT_GUILD_ID||null;
const parseJson=(v,fallback)=>{try{return JSON.parse(v||JSON.stringify(fallback))}catch{return fallback}};
const auth=(req,res,next)=>req.session.user?next():res.status(401).json({error:'unauthorized'});
const playerAuth=(req,res,next)=>req.session.player?next():res.status(401).json({error:'Connexion Discord requise'});
const allowed=(req,id)=>(req.session.guilds||[]).some(g=>g.id===id);
const publicHits=new Map();
function publicRate(req,res,next){const now=Date.now(),key=req.ip||'unknown',x=publicHits.get(key)||{at:now,count:0};if(now-x.at>60000){x.at=now;x.count=0}if(++x.count>40)return res.status(429).json({error:'Trop de requêtes. Réessaie dans une minute.'});publicHits.set(key,x);next()}
function publicScope(req){const id=publicGuildId();const requested=clean(req.query.guild_id||req.body?.guild_id||id,30);return id&&requested===id?id:null}

app.get('/auth/login',(req,res)=>{const p=new URLSearchParams({client_id:process.env.DISCORD_CLIENT_ID,response_type:'code',redirect_uri:process.env.DISCORD_REDIRECT_URI,scope:'identify guilds'});res.redirect(`https://discord.com/oauth2/authorize?${p}`)});
app.get('/auth/callback',async(req,res)=>{try{const body=new URLSearchParams({client_id:process.env.DISCORD_CLIENT_ID,client_secret:process.env.DISCORD_CLIENT_SECRET,grant_type:'authorization_code',code:req.query.code,redirect_uri:process.env.DISCORD_REDIRECT_URI});const tr=await fetch('https://discord.com/api/oauth2/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});const token=await tr.json();if(!tr.ok||!token.access_token)throw Error(token.error_description||'OAuth token absent');const headers={Authorization:`Bearer ${token.access_token}`};const [user,guilds]=await Promise.all([fetch('https://discord.com/api/users/@me',{headers}).then(r=>r.json()),fetch('https://discord.com/api/users/@me/guilds',{headers}).then(r=>r.json())]);req.session.user={id:user.id,username:user.username,avatar:user.avatar};req.session.guilds=Array.isArray(guilds)?guilds.filter(g=>{const p=BigInt(g.permissions||0);return(p&0x20n)!==0n||(p&0x8n)!==0n}):[];res.redirect('/admin')}catch(e){res.status(500).send(`OAuth Discord échoué : ${e.message}`)}});
app.get('/auth/player/login',(req,res)=>{const redirect=process.env.PLAYER_REDIRECT_URI||`${process.env.BASE_URL||'http://localhost:3000'}/auth/player/callback`;const p=new URLSearchParams({client_id:process.env.DISCORD_CLIENT_ID,response_type:'code',redirect_uri:redirect,scope:'identify'});res.redirect(`https://discord.com/oauth2/authorize?${p}`)});
app.get('/auth/player/callback',async(req,res)=>{try{const redirect=process.env.PLAYER_REDIRECT_URI||`${process.env.BASE_URL||'http://localhost:3000'}/auth/player/callback`;const body=new URLSearchParams({client_id:process.env.DISCORD_CLIENT_ID,client_secret:process.env.DISCORD_CLIENT_SECRET,grant_type:'authorization_code',code:req.query.code,redirect_uri:redirect});const tr=await fetch('https://discord.com/api/oauth2/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});const token=await tr.json();if(!tr.ok||!token.access_token)throw Error(token.error_description||'OAuth token absent');const user=await fetch('https://discord.com/api/users/@me',{headers:{Authorization:`Bearer ${token.access_token}`}}).then(r=>r.json());req.session.player={id:user.id,username:user.username,global_name:user.global_name||user.username,avatar:user.avatar};res.redirect('/suivi')}catch(e){res.status(500).send(`Connexion Discord échouée : ${e.message}`)}});
app.post('/auth/logout',(req,res)=>req.session.destroy(()=>res.json({ok:true})));
app.post('/auth/player/logout',(req,res)=>{delete req.session.player;res.json({ok:true})});
app.get('/api/me',auth,(req,res)=>res.json({user:req.session.user,guilds:req.session.guilds||[]}));
app.get('/api/public/me',(req,res)=>res.json({user:req.session.player||null}));

app.get('/',(req,res)=>res.sendFile(path.resolve('public/portal.html')));
app.get('/suivi',(req,res)=>res.sendFile(path.resolve('public/tracking.html')));
app.get('/admin',(req,res)=>res.sendFile(path.resolve('public/index.html')));
app.get('/recrutements',(req,res)=>res.sendFile(path.resolve('public/recrutements.html')));
app.get('/recrutement/:id',(req,res)=>res.sendFile(path.resolve('public/recrutement.html')));

app.get('/api/public/config',(req,res)=>res.json({guildId:publicGuildId(),brand:'LS CUSTOM',server:'Redside RP',player:!!req.session.player}));
app.get('/api/public/content',publicRate,(req,res)=>{const g=publicGuildId();res.json({news:getSetting(g,'news',''),description:getSetting(g,'server_description','')})});
app.get('/api/public/status',publicRate,async(req,res)=>{const url=process.env.FIVEM_SERVER_URL;if(!url)return res.json({configured:false,online:null,players:null,maxPlayers:null});try{const r=await fetch(`${url.replace(/\/$/,'')}/players.json`,{signal:AbortSignal.timeout(4000)});if(!r.ok)throw Error();const players=await r.json();res.json({configured:true,online:true,players:Array.isArray(players)?players.length:0,maxPlayers:Number(process.env.FIVEM_MAX_PLAYERS||0)||null})}catch{res.json({configured:true,online:false,players:0,maxPlayers:Number(process.env.FIVEM_MAX_PLAYERS||0)||null})}});
app.get('/api/public/recruitments',publicRate,(req,res)=>{const g=publicScope(req);if(!g)return res.status(403).json({error:'Serveur public invalide'});res.json(getRecruitments(g,'open').map(r=>({id:r.id,title:r.title,description:r.description,image:r.image_url||(r.image_path?`/uploads/${encodeURIComponent(path.basename(r.image_path))}`:null),status:r.status,created_at:r.created_at,questions:parseJson(r.questions_json,[])})))});
app.get('/api/public/recruitments/:id',publicRate,(req,res)=>{const r=getRecruitment(Number(req.params.id),publicGuildId());if(!r)return res.status(404).json({error:'Recrutement introuvable'});res.json({id:r.id,title:r.title,description:r.description,image:r.image_url||(r.image_path?`/uploads/${encodeURIComponent(path.basename(r.image_path))}`:null),status:r.status,created_at:r.created_at,questions:parseJson(r.questions_json,[])})});

app.post('/api/public/recruitments/:id/applications',publicRate,upload.array('attachments',5),(req,res)=>{try{const g=publicGuildId(),r=getRecruitment(Number(req.params.id),g);if(!g||!r)return res.status(404).json({error:'Recrutement introuvable'});if(r.status!=='open')return res.status(409).json({error:'Ce recrutement est fermé.'});const nom=clean(req.body.nom,60),prenom=clean(req.body.prenom,60),rpId=clean(req.body.rp_id,30),age=Number(req.body.age),discordId=clean(req.body.discord_id||req.session.player?.id,30),presentation=clean(req.body.presentation,2500),motivation=clean(req.body.motivation,3000),experience=clean(req.body.experience,2500);if(!nom||!prenom||!rpId||!/^\d{17,20}$/.test(discordId)||!presentation||!motivation||!experience||!Number.isInteger(age)||age<15||age>99)return res.status(400).json({error:'Tous les champs obligatoires doivent être correctement remplis.'});const identity=`discord:${discordId}`;if(hasRecentApplication(r.id,identity,30))return res.status(429).json({error:'Une candidature récente existe déjà pour ce recrutement avec ce compte Discord.'});const answers={nom,prenom,rp_id:rpId,age,discord_id:discordId,presentation,motivation,experience,source:req.session.player?'discord':'web'};for(const q of parseJson(r.questions_json,[])){const key=clean(q.key,40);const value=clean(req.body[key],3000);if(key&&q.required!==false&&!value)return res.status(400).json({error:`La question « ${q.label} » est obligatoire.`});if(key)answers[key]=value}const attachments=(req.files||[]).map(f=>({name:f.originalname,path:`/uploads/${path.basename(f.path)}`,size:f.size,mime:f.mimetype}));const a=createApplication({recruitmentId:r.id,guildId:g,userId:identity,username:req.session.player?.global_name||`${prenom} ${nom}`,answers,attachments});audit(g,identity,'public.application.created',String(a.id));notifyWebsiteApplication(a,r).catch(e=>console.error('Notification candidature:',e.message));res.status(201).json({ok:true,id:a.id,reference:`LSC-${String(a.id).padStart(5,'0')}`})}catch(e){console.error(e);res.status(500).json({error:'Impossible d’envoyer la candidature.'})}});
app.post('/api/public/tickets',publicRate,upload.array('attachments',5),(req,res)=>{try{const g=publicGuildId(),type=clean(req.body.type,30);if(!g||!['partnership','vip','support'].includes(type))return res.status(400).json({error:'Type de ticket invalide.'});const username=clean(req.body.username,80)||req.session.player?.global_name||'Visiteur',subject=clean(req.body.subject,140);if(!subject)return res.status(400).json({error:'Un sujet est obligatoire.'});let details={};if(type==='partnership')details={company:clean(req.body.company,120),contact:clean(req.body.contact,120),website:clean(req.body.website,300),proposal:clean(req.body.proposal,2500),budget:clean(req.body.budget,100),discord:clean(req.body.discord,80)};else if(type==='vip')details={name:clean(req.body.name,100),discord:clean(req.body.discord,80),rp_id:clean(req.body.rp_id,30),date:clean(req.body.date,40),people:clean(req.body.people,20),reason:clean(req.body.reason,2000)};else details={discord:clean(req.body.discord,80),message:clean(req.body.message,3000)};if(Object.values(details).some(v=>!v))return res.status(400).json({error:'Merci de remplir tous les champs demandés.'});const attachments=(req.files||[]).map(f=>({name:f.originalname,path:`/uploads/${path.basename(f.path)}`,size:f.size,mime:f.mimetype}));const t=createTicket({guildId:g,type,userId:req.session.player?.id||null,username,subject,details,attachments});audit(g,req.session.player?.id||null,`public.ticket.${type}`,String(t.id));notifyWebsiteTicket(t).catch(e=>console.error('Notification ticket:',e.message));res.status(201).json({ok:true,id:t.id,reference:`LSC-T-${String(t.id).padStart(5,'0')}`})}catch(e){console.error(e);res.status(500).json({error:'Impossible de créer le ticket.'})}});
app.get('/api/public/tracking',playerAuth,(req,res)=>{const g=publicGuildId();res.json({applications:getApplicationsForUser(g,`discord:${req.session.player.id}`).map(a=>({...a,answers:parseJson(a.answers_json,{}),attachments:parseJson(a.attachments_json,[])})),tickets:getTicketsForUser(g,req.session.player.id).map(t=>({...t,details:parseJson(t.details_json,{}),attachments:parseJson(t.attachments_json,[])}))})});

app.get('/api/guilds/:guildId/stats',auth,(req,res)=>allowed(req,req.params.guildId)?res.json(stats(req.params.guildId)):res.sendStatus(403));
app.get('/api/guilds/:guildId/recruitments',auth,(req,res)=>allowed(req,req.params.guildId)?res.json(getRecruitments(req.params.guildId,req.query.status||null)):res.sendStatus(403));
app.get('/api/guilds/:guildId/applications',auth,(req,res)=>{if(!allowed(req,req.params.guildId))return res.sendStatus(403);const applications=getApplications(req.params.guildId,req.query.status||null).map(a=>({...a,answers:parseJson(a.answers_json,{}),attachments:parseJson(a.attachments_json,[])}));res.json(applications)});
app.get('/api/guilds/:guildId/tickets',auth,(req,res)=>{if(!allowed(req,req.params.guildId))return res.sendStatus(403);res.json(getTickets(req.params.guildId,req.query.status||null).map(t=>({...t,details:parseJson(t.details_json,{}),attachments:parseJson(t.attachments_json,[])})))});
app.get('/api/guilds/:guildId/audit',auth,(req,res)=>allowed(req,req.params.guildId)?res.json(getAuditLogs(req.params.guildId,req.query.limit)):res.sendStatus(403));
app.post('/api/guilds/:guildId/tickets/:id/status',auth,(req,res)=>{const g=req.params.guildId;if(!allowed(req,g))return res.sendStatus(403);if(!['open','closed','pending'].includes(req.body.status))return res.status(400).json({error:'invalid status'});const t=setTicketStatus(Number(req.params.id),g,req.body.status);if(!t)return res.status(404).json({error:'Ticket introuvable'});audit(g,req.session.user.id,'ticket.status',`${t.id}:${req.body.status}`);res.json(t)});
app.post('/api/guilds/:guildId/recruitments',auth,upload.single('image'),async(req,res)=>{let created=false;try{const g=req.params.guildId;if(!allowed(req,g))return res.sendStatus(403);const title=clean(req.body.title,120),description=clean(req.body.description,4000),imageUrl=clean(req.body.imageUrl,2000);let questions=parseJson(req.body.questions_json,[]);questions=Array.isArray(questions)?questions.slice(0,20).map((q,i)=>({key:clean(q.key,40)||`question_${i+1}`,label:clean(q.label,180),type:['text','textarea','number'].includes(q.type)?q.type:'text',required:q.required!==false})).filter(q=>q.label):[];if(!title||!description)return res.status(400).json({error:'Titre et description obligatoires'});if(imageUrl&&!/^https:\/\//i.test(imageUrl))return res.status(400).json({error:'L’URL image doit utiliser HTTPS'});const r=createRecruitment({guildId:g,title,description,imageUrl:imageUrl||null,imagePath:req.file?.path,createdBy:req.session.user.id,questions});created=true;audit(g,req.session.user.id,'dashboard.recruitment.created',String(r.id));if(req.body.publish==='true'){try{await publishFromDashboard(g,r);audit(g,req.session.user.id,'dashboard.recruitment.published',String(r.id))}catch(e){return res.status(201).json({...r,published:false,publishError:e.message})}}res.status(201).json({...r,published:req.body.publish==='true'})}catch(e){if(!created&&req.file)fs.rmSync(req.file.path,{force:true});res.status(500).json({error:e.message||'Erreur serveur'})}});
app.post('/api/guilds/:guildId/recruitments/:id/publish',auth,async(req,res)=>{try{const g=req.params.guildId;if(!allowed(req,g))return res.sendStatus(403);const r=getRecruitment(Number(req.params.id),g);if(!r)return res.status(404).json({error:'Recrutement introuvable'});const message=await publishFromDashboard(g,r);audit(g,req.session.user.id,'dashboard.recruitment.published',String(r.id));res.json({ok:true,messageId:message.id,recruitmentId:r.id,publicUrl:`/recrutement/${r.id}`})}catch(e){res.status(503).json({error:e.message||'Publication Discord impossible'})}});
app.post('/api/guilds/:guildId/recruitments/:id/status',auth,(req,res)=>{const g=req.params.guildId;if(!allowed(req,g))return res.sendStatus(403);const status=clean(req.body.status||req.query.status,20).toLowerCase();if(!['open','closed'].includes(status))return res.status(400).json({error:'invalid status'});const r=setRecruitmentStatus(Number(req.params.id),g,status);if(!r)return res.status(404).json({error:'Recrutement introuvable'});audit(g,req.session.user.id,'recruitment.status',`${r.id}:${status}`);res.json({ok:true,recruitment:r})});
app.post('/api/guilds/:guildId/applications/:id/status',auth,(req,res)=>{const g=req.params.guildId;if(!allowed(req,g))return res.sendStatus(403);if(!['pending','accepted','rejected'].includes(req.body.status))return res.status(400).json({error:'invalid status'});const r=updateApplication(Number(req.params.id),g,req.body.status,req.session.user.id);if(!r)return res.status(404).json({error:'Candidature introuvable'});audit(g,req.session.user.id,'application.status',`${r.id}:${req.body.status}`);notifyWebsiteApplicationStatus(r,req.body.status).catch(e=>console.error('Notification statut:',e.message));res.json({...r,answers:parseJson(r.answers_json,{})})});
app.post('/api/guilds/:guildId/settings',auth,(req,res)=>{const g=req.params.guildId;if(!allowed(req,g))return res.sendStatus(403);for(const[k,v]of Object.entries(req.body))if(['recruitment_channel','logs_channel','tickets_channel','recruiter_role','news','server_description'].includes(k))setSetting(g,k,String(v||''));audit(g,req.session.user.id,'settings.updated',Object.keys(req.body).join(','));res.json({ok:true})});
app.get('/api/guilds/:guildId/settings',auth,(req,res)=>allowed(req,req.params.guildId)?res.json({recruitment_channel:getSetting(req.params.guildId,'recruitment_channel',''),logs_channel:getSetting(req.params.guildId,'logs_channel',''),tickets_channel:getSetting(req.params.guildId,'tickets_channel',''),recruiter_role:getSetting(req.params.guildId,'recruiter_role',''),news:getSetting(req.params.guildId,'news',''),server_description:getSetting(req.params.guildId,'server_description','')}):res.sendStatus(403));
app.get(/.*/,(req,res)=>res.sendFile(path.resolve('public/portal.html')));
export function startDashboard(){app.listen(Number(process.env.PORT||3000),()=>console.log(`🌐 Site : ${process.env.BASE_URL||`http://localhost:${process.env.PORT||3000}`}`))}
