import express from 'express';
import session from 'express-session';
import multer from 'multer';
import path from 'node:path';
import fs from 'node:fs';
import crypto from 'node:crypto';
import db,{getRecruitments,getRecruitment,createRecruitment,createApplication,hasRecentApplication,getApplications,updateApplication,getSetting,setSetting,stats,audit,createTicket,getTickets,setTicketStatus} from './db.js';
import {publishFromDashboard,notifyWebsiteApplication,notifyWebsiteTicket} from './bot.js';

const app=express();
const uploadDir=path.resolve('data/uploads'); fs.mkdirSync(uploadDir,{recursive:true});
const upload=multer({storage:multer.diskStorage({destination:uploadDir,filename:(req,file,cb)=>cb(null,`${Date.now()}-${crypto.randomUUID()}${path.extname(file.originalname).toLowerCase()}`)}),limits:{fileSize:8*1024*1024},fileFilter:(req,file,cb)=>cb(null,/^image\/(png|jpe?g|webp|gif)$/.test(file.mimetype))});
app.use(express.json({limit:'1mb'})); app.use(express.urlencoded({extended:true})); app.use(express.static('public')); app.use('/uploads',express.static(uploadDir));
app.use(session({secret:process.env.SESSION_SECRET||'dev-secret',resave:false,saveUninitialized:false,cookie:{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:86400000}}));
function auth(req,res,next){if(!req.session.user)return res.status(401).json({error:'unauthorized'});next()}
function allowed(req,id){return(req.session.guilds||[]).some(g=>g.id===id)}
function clean(v,max){return String(v??'').trim().slice(0,max)}
function publicGuildId(){return process.env.DEFAULT_GUILD_ID||null}
const publicHits=new Map();
function publicRate(req,res,next){const key=req.ip||'unknown';const now=Date.now();const item=publicHits.get(key)||{at:now,count:0};if(now-item.at>60000){item.at=now;item.count=0}item.count++;publicHits.set(key,item);if(item.count>30)return res.status(429).json({error:'Trop de requêtes. Réessaie dans une minute.'});next()}

app.get('/auth/login',(req,res)=>{const p=new URLSearchParams({client_id:process.env.DISCORD_CLIENT_ID,response_type:'code',redirect_uri:process.env.DISCORD_REDIRECT_URI,scope:'identify guilds'});res.redirect('https://discord.com/oauth2/authorize?'+p)});
app.get('/auth/callback',async(req,res)=>{try{const body=new URLSearchParams({client_id:process.env.DISCORD_CLIENT_ID,client_secret:process.env.DISCORD_CLIENT_SECRET,grant_type:'authorization_code',code:req.query.code,redirect_uri:process.env.DISCORD_REDIRECT_URI});const tr=await fetch('https://discord.com/api/oauth2/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});const token=await tr.json();if(!tr.ok||!token.access_token)throw Error(token.error_description||'OAuth token absent');const headers={Authorization:`Bearer ${token.access_token}`};const[user,guilds]=await Promise.all([fetch('https://discord.com/api/users/@me',{headers}).then(r=>r.json()),fetch('https://discord.com/api/users/@me/guilds',{headers}).then(r=>r.json())]);req.session.user={id:user.id,username:user.username,avatar:user.avatar};req.session.guilds=Array.isArray(guilds)?guilds.filter(g=>{const p=BigInt(g.permissions||0);return(p&0x20n)!==0n||(p&0x8n)!==0n}):[];res.redirect('/admin')}catch(e){res.status(500).send('OAuth Discord échoué : '+e.message)}});
app.post('/auth/logout',(req,res)=>req.session.destroy(()=>res.json({ok:true}))); app.get('/api/me',auth,(req,res)=>res.json({user:req.session.user,guilds:req.session.guilds||[]}));

app.get('/',(req,res)=>res.sendFile(path.resolve('public/portal.html')));
app.get('/admin',(req,res)=>res.sendFile(path.resolve('public/index.html')));
app.get('/recrutements',(req,res)=>res.sendFile(path.resolve('public/recrutements.html')));
app.get('/recrutement/:id',(req,res)=>res.sendFile(path.resolve('public/recrutement.html')));
app.get('/api/public/config',(req,res)=>res.json({guildId:publicGuildId(),brand:'LS CUSTOM',server:'Redside RP'}));
app.get('/api/public/recruitments',publicRate,(req,res)=>{const guildId=clean(req.query.guild_id||publicGuildId(),30);if(!guildId)return res.json([]);const rows=getRecruitments(guildId,'open').map(r=>({id:r.id,title:r.title,description:r.description,image:r.image_url||(r.image_path?`/uploads/${encodeURIComponent(path.basename(r.image_path))}`:null),status:r.status,created_at:r.created_at}));res.json(rows)});
app.get('/api/public/recruitments/:id',publicRate,(req,res)=>{const r=db.prepare('SELECT id,guild_id,title,description,image_url,image_path,status,created_at FROM recruitments WHERE id=?').get(Number(req.params.id));if(!r)return res.status(404).json({error:'Recrutement introuvable'});const image=r.image_url||(r.image_path?`/uploads/${encodeURIComponent(path.basename(r.image_path))}`:null);res.json({id:r.id,guild_id:r.guild_id,title:r.title,description:r.description,image,status:r.status,created_at:r.created_at})});
app.post('/api/public/recruitments/:id/applications',publicRate,(req,res)=>{try{const r=db.prepare('SELECT * FROM recruitments WHERE id=?').get(Number(req.params.id));if(!r)return res.status(404).json({error:'Recrutement introuvable'});if(r.status!=='open')return res.status(409).json({error:'Ce recrutement est fermé.'});const nom=clean(req.body.nom,60),prenom=clean(req.body.prenom,60),rpId=clean(req.body.rp_id,30),age=Number(req.body.age),discordId=clean(req.body.discord_id,30),presentation=clean(req.body.presentation,2500),motivation=clean(req.body.motivation,3000),experience=clean(req.body.experience,2500);if(!nom||!prenom||!rpId||!discordId||!/^\d{17,20}$/.test(discordId)||!presentation||!motivation||!experience||!Number.isInteger(age)||age<15||age>99)return res.status(400).json({error:'Tous les champs obligatoires doivent être correctement remplis.'});const identity=`web:${discordId}:${rpId}`;if(hasRecentApplication(r.id,identity,10))return res.status(429).json({error:'Une candidature vient déjà d’être envoyée récemment avec ces identifiants.'});const a=createApplication({recruitmentId:r.id,guildId:r.guild_id,userId:identity,username:`${prenom} ${nom}`,answers:{nom,prenom,rp_id:rpId,age,discord_id:discordId,presentation,motivation,experience,source:'web'}});audit(r.guild_id,identity,'public.application.created',String(a.id));notifyWebsiteApplication(a,r).catch(e=>console.error('Notification candidature:',e.message));res.status(201).json({ok:true,id:a.id,reference:`LSC-${String(a.id).padStart(5,'0')}`})}catch(e){console.error('Candidature publique:',e);res.status(500).json({error:'Impossible d’envoyer la candidature.'})}});
app.post('/api/public/tickets',publicRate,(req,res)=>{try{const guildId=clean(req.body.guild_id||publicGuildId(),30);const type=clean(req.body.type,30);const allowedTypes=['partnership','vip','support'];if(!guildId||!allowedTypes.includes(type))return res.status(400).json({error:'Type de ticket ou serveur invalide.'});const username=clean(req.body.username,80)||'Visiteur';const subject=clean(req.body.subject,140);if(!subject)return res.status(400).json({error:'Un sujet est obligatoire.'});let details={};if(type==='partnership')details={company:clean(req.body.company,120),contact:clean(req.body.contact,120),website:clean(req.body.website,300),proposal:clean(req.body.proposal,2500),budget:clean(req.body.budget,100),discord:clean(req.body.discord,80)};else if(type==='vip')details={name:clean(req.body.name,100),discord:clean(req.body.discord,80),rp_id:clean(req.body.rp_id,30),date:clean(req.body.date,40),people:clean(req.body.people,20),reason:clean(req.body.reason,2000)};else details={discord:clean(req.body.discord,80),message:clean(req.body.message,3000)};if(Object.values(details).some(v=>!v))return res.status(400).json({error:'Merci de remplir tous les champs demandés.'});const t=createTicket({guildId,type,userId:null,username,subject,details});audit(guildId,null,`public.ticket.${type}`,String(t.id));notifyWebsiteTicket(t).catch(e=>console.error('Notification ticket:',e.message));res.status(201).json({ok:true,id:t.id,reference:`LSC-T-${String(t.id).padStart(5,'0')}`})}catch(e){console.error('Ticket public:',e);res.status(500).json({error:'Impossible de créer le ticket.'})}});

app.get('/api/guilds/:guildId/stats',auth,(req,res)=>allowed(req,req.params.guildId)?res.json(stats(req.params.guildId)):res.sendStatus(403));
app.get('/api/guilds/:guildId/recruitments',auth,(req,res)=>allowed(req,req.params.guildId)?res.json(getRecruitments(req.params.guildId,req.query.status||null)):res.sendStatus(403));
app.get('/api/guilds/:guildId/applications',auth,(req,res)=>allowed(req,req.params.guildId)?res.json(getApplications(req.params.guildId,req.query.status||null)):res.sendStatus(403));
app.get('/api/guilds/:guildId/tickets',auth,(req,res)=>allowed(req,req.params.guildId)?res.json(getTickets(req.params.guildId,req.query.status||null).map(t=>({...t,details:JSON.parse(t.details_json||'{}')}))):res.sendStatus(403));
app.post('/api/guilds/:guildId/tickets/:id/status',auth,(req,res)=>{const guildId=req.params.guildId;if(!allowed(req,guildId))return res.sendStatus(403);if(!['open','closed','pending'].includes(req.body.status))return res.status(400).json({error:'invalid status'});const t=setTicketStatus(Number(req.params.id),guildId,req.body.status);if(!t)return res.status(404).json({error:'Ticket introuvable'});audit(guildId,req.session.user.id,'ticket.status',`${t.id}:${req.body.status}`);res.json(t)});
app.post('/api/guilds/:guildId/recruitments',auth,upload.single('image'),async(req,res)=>{let created=false;try{const guildId=req.params.guildId;if(!allowed(req,guildId))return res.sendStatus(403);const title=clean(req.body.title,120),description=clean(req.body.description,4000),imageUrl=clean(req.body.imageUrl,2000);if(!title||!description)return res.status(400).json({error:'Titre et description obligatoires'});if(imageUrl&&!/^https:\/\//i.test(imageUrl))return res.status(400).json({error:'L’URL image doit utiliser HTTPS'});const r=createRecruitment({guildId,title,description,imageUrl:imageUrl||null,imagePath:req.file?.path,createdBy:req.session.user.id});created=true;audit(guildId,req.session.user.id,'dashboard.recruitment.created',String(r.id));if(req.body.publish==='true'){try{await publishFromDashboard(guildId,r);audit(guildId,req.session.user.id,'dashboard.recruitment.published',String(r.id))}catch(e){return res.status(503).json({error:e.message,recruitment:r,published:false})}}return res.status(201).json({...r,published:req.body.publish==='true'})}catch(e){if(!created&&req.file)fs.rmSync(req.file.path,{force:true});console.error('Création recrutement:',e);return res.status(500).json({error:e.message||'Erreur serveur'})}});
app.post('/api/guilds/:guildId/recruitments/:id/publish',auth,async(req,res)=>{try{const guildId=req.params.guildId;if(!allowed(req,guildId))return res.sendStatus(403);const r=getRecruitments(guildId).find(x=>x.id===Number(req.params.id));if(!r)return res.status(404).json({error:'Recrutement introuvable'});const message=await publishFromDashboard(guildId,r);audit(guildId,req.session.user.id,'dashboard.recruitment.published',String(r.id));res.json({ok:true,messageId:message.id,recruitmentId:r.id,publicUrl:`/recrutement/${r.id}`})}catch(e){console.error('Publication dashboard:',e);res.status(503).json({error:e.message||'Publication Discord impossible'})}});
app.post('/api/guilds/:guildId/applications/:id/status',auth,(req,res)=>{const guildId=req.params.guildId;if(!allowed(req,guildId))return res.sendStatus(403);if(!['pending','accepted','rejected'].includes(req.body.status))return res.status(400).json({error:'invalid status'});const r=updateApplication(Number(req.params.id),guildId,req.body.status,req.session.user.id);if(!r)return res.status(404).json({error:'Candidature introuvable'});audit(guildId,req.session.user.id,'application.status',`${r.id}:${req.body.status}`);res.json(r)});
app.post('/api/guilds/:guildId/settings',auth,(req,res)=>{const guildId=req.params.guildId;if(!allowed(req,guildId))return res.sendStatus(403);for(const[k,v]of Object.entries(req.body))if(['recruitment_channel','logs_channel','tickets_channel','recruiter_role'].includes(k))setSetting(guildId,k,String(v||''));res.json({ok:true})});
app.get('/api/guilds/:guildId/settings',auth,(req,res)=>allowed(req,req.params.guildId)?res.json({recruitment_channel:getSetting(req.params.guildId,'recruitment_channel',''),logs_channel:getSetting(req.params.guildId,'logs_channel',''),tickets_channel:getSetting(req.params.guildId,'tickets_channel',''),recruiter_role:getSetting(req.params.guildId,'recruiter_role','')}):res.sendStatus(403));
app.get(/.*/,(req,res)=>res.sendFile(path.resolve('public/portal.html')));
export function startDashboard(){app.listen(Number(process.env.PORT||3000),()=>console.log(`🌐 Site : ${process.env.BASE_URL||`http://localhost:${process.env.PORT||3000}`}`))}
